
public class ColorOptionsFrame extends javax.swing.JFrame {

    /**
     * Creates new form ColorOptionsFrame
     */
    public ColorOptionsFrame(Display display) {
        initComponents();
        
        skyColorButton.setBackground(display.skyColor);
        groundColorButton.setBackground(display.groundColor);
        toraColorButton.setBackground(display.toraColor);
        todaColorButton.setBackground(display.todaColor);
        asdaColorButton.setBackground(display.asdaColor);
        ldaColorButton.setBackground(display.ldaColor);
        lineColorButton.setBackground(display.lineColor);
        obstacleColorButton.setBackground(display.obstacleColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        runwayColorLabel = new javax.swing.JLabel();
        runwayColorLabel1 = new javax.swing.JLabel();
        runwayColorLabel2 = new javax.swing.JLabel();
        runwayColorLabel3 = new javax.swing.JLabel();
        runwayColorLabel4 = new javax.swing.JLabel();
        runwayColorLabel5 = new javax.swing.JLabel();
        runwayColorLabel6 = new javax.swing.JLabel();
        runwayColorLabel7 = new javax.swing.JLabel();
        runwayColorLabel8 = new javax.swing.JLabel();
        runwayColorButton = new javax.swing.JButton();
        skyColorButton = new javax.swing.JButton();
        groundColorButton = new javax.swing.JButton();
        toraColorButton = new javax.swing.JButton();
        todaColorButton = new javax.swing.JButton();
        asdaColorButton = new javax.swing.JButton();
        ldaColorButton = new javax.swing.JButton();
        lineColorButton = new javax.swing.JButton();
        obstacleColorButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        runwayColorLabel.setText("Runway Colour");

        runwayColorLabel1.setText("Sky Colour");

        runwayColorLabel2.setText("Ground Colour");

        runwayColorLabel3.setText("TORA Colour");

        runwayColorLabel4.setText("TODA Colour");

        runwayColorLabel5.setText("ASDA Colour");

        runwayColorLabel6.setText("LDA Colour");

        runwayColorLabel7.setText("Line Marking Colour");

        runwayColorLabel8.setText("Obstacle Colour");

        runwayColorButton.setText("Colour");

        skyColorButton.setText("Colour");

        groundColorButton.setText("Colour");

        toraColorButton.setText("Colour");

        todaColorButton.setText("Colour");

        asdaColorButton.setText("Colour");

        ldaColorButton.setText("Colour");

        lineColorButton.setText("Colour");

        obstacleColorButton.setText("Colour");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(runwayColorLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(obstacleColorButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(runwayColorLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lineColorButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(runwayColorLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ldaColorButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(runwayColorLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(asdaColorButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(runwayColorLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(todaColorButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(runwayColorLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(toraColorButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(runwayColorLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(groundColorButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(runwayColorLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(skyColorButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(runwayColorLabel)
                        .addGap(87, 87, 87)
                        .addComponent(runwayColorButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(runwayColorLabel)
                        .addComponent(runwayColorButton))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(runwayColorLabel1)
                    .addComponent(skyColorButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(runwayColorLabel2)
                    .addComponent(groundColorButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(runwayColorLabel3)
                    .addComponent(toraColorButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(runwayColorLabel4)
                    .addComponent(todaColorButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(runwayColorLabel5)
                    .addComponent(asdaColorButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(runwayColorLabel6)
                    .addComponent(ldaColorButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(runwayColorLabel7)
                    .addComponent(lineColorButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(runwayColorLabel8)
                    .addComponent(obstacleColorButton))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void runwayColorButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 


    // Variables declaration - do not modify                     
    private javax.swing.JButton asdaColorButton;
    private javax.swing.JButton groundColorButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton ldaColorButton;
    private javax.swing.JButton lineColorButton;
    private javax.swing.JButton obstacleColorButton;
    private javax.swing.JButton runwayColorButton;
    private javax.swing.JLabel runwayColorLabel;
    private javax.swing.JLabel runwayColorLabel1;
    private javax.swing.JLabel runwayColorLabel2;
    private javax.swing.JLabel runwayColorLabel3;
    private javax.swing.JLabel runwayColorLabel4;
    private javax.swing.JLabel runwayColorLabel5;
    private javax.swing.JLabel runwayColorLabel6;
    private javax.swing.JLabel runwayColorLabel7;
    private javax.swing.JLabel runwayColorLabel8;
    private javax.swing.JButton skyColorButton;
    private javax.swing.JButton todaColorButton;
    private javax.swing.JButton toraColorButton;
    // End of variables declaration                   
}
